image: mcr.microsoft.com/dotnet/core/sdk:3.1

before_script:
  - $PSVersionTable.PSVersion
  - dotnet --version
  - nuget help | select-string Version

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  script:
    - dotnet build -c Release

test:
  stage: test
  script:
    - # Команды для запуска тестов вашего проекта

publish:
  stage: publish
  script:
    - # Команды для создания артефакта (например, исполняемого файла или архива)

deploy:
  stage: deploy
  script:
    - # Команды для ручного развертывания на удаленной машине

# Добавьте другие настройки CI/CD, если необходимо
