image: mcr.microsoft.com/dotnet/core/sdk:3.1

before_script:
  - $PSVersionTable.PSVersion
  - dotnet --version
  - nuget help | select-string Version

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  script:
    - dotnet build -c Release

test:
  stage: test
  script:
    - dotnet --version

publish:
  stage: publish
  script:
    - dotnet --version 

deploy:
  stage: deploy
  script:
    - dotnet --version